language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-4.8
  - if [ $CC == 'gcc' ]; then export CC=gcc-4.8; fi;
  - bundle install
  - make clean
  - make start_simulator
script:
  - make all
