os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: osx
language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
install:
  - ruby ./config/travis_install.rb
  - bundle install
script:
  - bundle exec rake verbose ci
