language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-4.8.2
  - bundle install
script:
  - make start_simulator
  - make all
